config/routes.rb
Rails.application.routes.draw do
  root to: 'messages#index'

  resources :contacts
  resources :messages

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
  has_many :sent_messages
  has_many :messages, through: :sent_messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :body, presence: true
  validates :from, presence: true
  has_many :sent_messages
  has_many :contacts, through: :sent_messages
end

app/models/sent_message.rb
class SentMessage < ActiveRecord::Base
  belongs_to :contact
  belongs_to :message
  validates :to, presence: true

  before_create :send_message

  def display_recipient
    contact.nil? ? to : contact.first_name + ' ' + contact.last_name
  end

  private

    def send_message
      begin
        response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => self.message.body,
          :To => to,
          :From => self.message.from }
          ).execute
        rescue RestClient::BadRequest => error
          message = JSON.parse(error.response)['message']
          errors.add(:base, message)
          false
        end
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contacts_path
    else
      render :new
    end
  end

  private
    def contact_params
      params.require(:contact)
            .permit(:first_name, :last_name, :phone_number)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new()
    @sent_message = SentMessage.new(
      to: params[:to],
      contact_id: params[:contact_id]
    )
    @message.sent_messages << @sent_message
  end

  def create
    recipients = message_params[:to].split(/,\s*/)

    @message.new(
      from: message_params[:from],
      body: message_params[:body]
    )

    recipients.each do |recipient|
      sent_message = SentMessage.new(
        to: recipient,
        contact_id: message_params[:contact_id],
        message_id: @message.id
      )

      if sent_message.save && @message.save
        next
      else
        render :new
      end
    end

################################################

    # recipients.each do |recipient|
    #   @message = Message.new(
    #     to: recipient,
    #     from: message_params[:from],
    #     body: message_params[:body],
    #     contact_id: message_params[:contact_id]
    #   )
    #   @message.save ? next : (render :new)
    # end

    ################################################

    # @message = Message.new(message_params)
    #
    # if @message.save
    #   redirect_to messages_path
    # else
    #   render :new
    # end
  end

private
  def message_params
    params.require(:message).permit(:to, :from, :body, :contact_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_contact.html.erb
<li>
  <%= contact.last_name %>, <%= contact.first_name %> |
    <%= link_to contact.phone_number,
      new_message_path(to: contact.phone_number, contact_id: contact.id) %>
</li>

app/views/contacts/_form.html.erb
<%= render 'layouts/errors', object: @contact %>

<div class="row">
  <div class='col-md-6'>
    <%= form_for @contact do |f| %>
      <div class='form-group'>
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: 'form-control' %>
      </div>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/contacts/index.html.erb
<h3>Contact List:</h3>

<ul id="all_contacts">
  <%= render @contacts %>
</ul>

<br>
<%= link_to "Add New Contact", new_contact_path, class: "btn btn-info"%>

app/views/contacts/new.html.erb
<h3>New Contact</h3>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Text App", root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Contacts", contacts_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Text App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>

  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>

app/views/messages/_form.html.erb
<%= render 'layouts/errors', object: @message %>

<div class="row">
  <div class='col-md-6'>
    <%= form_for @message do |f| %>
      <%= f.hidden_field :contact_id,
        value: @sent_message.contact_id %>
      <div class='form-group'>
        <%= f.label :to %>
        <%= f.text_field :to, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :from %>
        <%= f.text_field :from, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/messages/_message.html.erb
<li>From: <%= message.from %> | To:
  <% message.sent_messages.each_with_index do |recipient, i| %>
    <% if i == 0 %>
      <%= recipient.display_recipient %>
    <% else %>
      , <%= recipient.display_recipient %>
    <% end %>
  <% end %>
  | Message: <%= message.body  %></li>

app/views/messages/index.html.erb
<h3>Sent Messages:</h3>

<ul id="all_messages">
  <%= render @messages %>
</ul>

<br>
<%= link_to "Send New Message", new_message_path, class: "btn btn-info"%>

app/views/messages/new.html.erb
<h3>New Message</h3>

<%= render 'form' %>